wsgi/satchmo/satchmo/apps/payment/modules/sagepay/urls.py
from django.conf.urls import patterns
from satchmo_store.shop.satchmo_settings import get_satchmo_setting

ssl = get_satchmo_setting('SSL', default_value=False)

urlpatterns = patterns('',
     (r'^$', 'payment.modules.sagepay.views.pay_ship_info',
        {'SSL':ssl}, 'SAGEPAY_satchmo_checkout-step2'),

     (r'^confirm/$', 'payment.modules.sagepay.views.confirm_info',
        {'SSL':ssl}, 'SAGEPAY_satchmo_checkout-step3'),

    (r'^secure3d/$', 'payment.modules.sagepay.views.confirm_secure3d',
       {'SSL':ssl}, 'SAGEPAY_satchmo_checkout-secure3d'),

     (r'^success/$', 'payment.views.checkout.success',
        {'SSL':ssl}, 'SAGEPAY_satchmo_checkout-success'),
)

wsgi/satchmo/satchmo/apps/payment/urls.py
from django.conf.urls import patterns, url
from django.db import models
from livesettings import config_value
from satchmo_store.shop.satchmo_settings import get_satchmo_setting
import logging

log = logging.getLogger('payment.urls')

ssl = get_satchmo_setting('SSL', default_value=False)

urlpatterns = patterns('payment.views',
     (r'^$', 'contact.contact_info_view', {'SSL': ssl}, 'satchmo_checkout-step1'),
     (r'^success/$', 'checkout.success', {'SSL' : ssl}, 'satchmo_checkout-success'),
     (r'custom/charge/(?P<orderitem_id>\d+)/$', 'balance.charge_remaining', {}, 'satchmo_charge_remaining'),
     (r'custom/charge/$', 'balance.charge_remaining_post', {}, 'satchmo_charge_remaining_post'),
     (r'^balance/(?P<order_id>\d+)/$', 'balance.balance_remaining_order', {'SSL' : ssl}, 'satchmo_balance_remaining_order'),
     (r'^balance/$', 'balance.balance_remaining', {'SSL' : ssl}, 'satchmo_balance_remaining'),
     (r'^cron/$', 'cron.cron_rebill', {}, 'satchmo_cron_rebill'),
     (r'^mustlogin/$', 'contact.authentication_required', {'SSL' : ssl}, 'satchmo_checkout_auth_required'),
)

# now add all enabled module payment settings

def make_urlpatterns():
    patterns = []
    for app in models.get_apps():
        if hasattr(app, 'PAYMENT_PROCESSOR'):
            parts = app.__name__.split('.')
            key = parts[-2].upper()
            modulename = 'PAYMENT_%s' % key
            name = app.__name__
            name = name[:name.rfind('.')]
            #log.debug('payment module=%s, key=%s', modulename, key)
            # BJK: commenting out Bursar settings here
            # try:
            #     cfg = config_get(modulename, 'INTERFACE_MODULE')
            #     interface = cfg.editor_value
            # except SettingNotSet:
            #     interface = name[:name.rfind('.')]
            # urlmodule = "%s.urls" % interface
            urlmodule = '.'.join(parts[:-1]) + '.urls'
            urlbase = config_value(modulename, 'URL_BASE')
            log.debug('Found payment processor: %s, adding urls at %s', key, urlbase)
            patterns.append(url(urlbase, [urlmodule, '', '']))
    return tuple(patterns)

urlpatterns += make_urlpatterns()

wsgi/satchmo/satchmo/apps/payment/models.py
"""
Stores details about the available payment options.
Also stores credit card info in an encrypted format.
"""

from Crypto.Cipher import Blowfish
from datetime import datetime
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from livesettings import config_value, config_choice_values, SettingNotSet
from satchmo_utils.iterchoices import iterchoices_db
import payment.config
from satchmo_store.contact.models import Contact
import base64
import config
import keyedcache
import logging
import satchmo_utils.sslurllib

log = logging.getLogger('payment.models')
        
class PaymentOption(models.Model):
    """
    If there are multiple options - CC, Cash, COD, etc this class allows
    configuration.
    """
    description = models.CharField(_("Description"), max_length=20)
    active = models.BooleanField(_("Active"), 
        help_text=_("Should this be displayed as an option for the user?"))
    optionName = models.CharField(_("Option Name"), max_length=20, choices=iterchoices_db(payment.config.labelled_gateway_choices),
        unique=True, 
        help_text=_("The class name as defined in payment.py"))
    sortOrder = models.IntegerField(_("Sort Order"))
    
    class Meta:
        verbose_name = _("Payment Option")
        verbose_name_plural = _("Payment Options")

class CreditCardDetail(models.Model):
    """
    Stores an encrypted CC number, its information, and its
    displayable number.
    """
    orderpayment = models.ForeignKey('shop.OrderPayment', unique=True, 
        related_name="creditcards")
    credit_type = models.CharField(_("Credit Card Type"), max_length=16, choices=iterchoices_db(payment.config.credit_choices))
    display_cc = models.CharField(_("CC Number (Last 4 digits)"),
        max_length=4, )
    encrypted_cc = models.CharField(_("Encrypted Credit Card"),
        max_length=40, blank=True, null=True, editable=False)
    expire_month = models.IntegerField(_("Expiration Month"))
    expire_year = models.IntegerField(_("Expiration Year"))
    card_holder = models.CharField(_("card_holder Name"), max_length=60, blank=True)
    start_month = models.IntegerField(_("Start Month"), blank=True, null=True)
    start_year = models.IntegerField(_("Start Year"), blank=True, null=True)
    issue_num = models.CharField(blank=True, null=True, max_length=2)
    
    def storeCC(self, ccnum):
        """Take as input a valid cc, encrypt it and store the last 4 digits in a visible form"""
        self.display_cc = ccnum[-4:]
        encrypted_cc = _encrypt_code(ccnum)
        if config_value('PAYMENT', 'STORE_CREDIT_NUMBERS'):
            self.encrypted_cc = encrypted_cc
        else:
            standin = "%s%i%i%i" % (self.display_cc, self.expire_month, self.expire_year, self.orderpayment.id)
            self.encrypted_cc = _encrypt_code(standin)
            key = _encrypt_code(standin + '-card')
            keyedcache.cache_set(key, skiplog=True, length=60*60, value=encrypted_cc)
    
    def setCCV(self, ccv):
        """Put the CCV in the cache, don't save it for security/legal reasons."""
        if not self.encrypted_cc:
            raise ValueError('CreditCardDetail expecting a credit card number to be stored before storing CCV')
            
        keyedcache.cache_set(self.encrypted_cc, skiplog=True, length=60*60, value=ccv)
    
    def getCCV(self):
        try:
            ccv = keyedcache.cache_get(self.encrypted_cc)
        except keyedcache.NotCachedError:
            ccv = ""

        return ccv
    
    ccv = property(fget=getCCV, fset=setCCV)
    
    def _decryptCC(self):
        ccnum = _decrypt_code(self.encrypted_cc)
        if not config_value('PAYMENT', 'STORE_CREDIT_NUMBERS'):
            try:
                key = _encrypt_code(ccnum + '-card')
                encrypted_ccnum = keyedcache.cache_get(key)
                ccnum = _decrypt_code(encrypted_ccnum)
            except keyedcache.NotCachedError:
                ccnum = ""
        return ccnum
                
    decryptedCC = property(_decryptCC) 

    def _expireDate(self):
        return(str(self.expire_month) + "/" + str(self.expire_year))
    expirationDate = property(_expireDate)
    
    class Meta:
        verbose_name = _("Credit Card")
        verbose_name_plural = _("Credit Cards")

def _decrypt_code(code):
    """Decrypt code encrypted by _encrypt_code"""
    # In some blowfish implementations, > 56 char keys can cause problems
    secret_key = settings.SECRET_KEY[:56]
    encryption_object = Blowfish.new(secret_key)
    # strip padding from decrypted credit card number
    return encryption_object.decrypt(base64.b64decode(code)).rstrip('X')

def _encrypt_code(code):
    """Quick encrypter for CC codes or code fragments"""
    # In some blowfish implementations, > 56 char keys can cause problems
    secret_key = settings.SECRET_KEY[:56]
    encryption_object = Blowfish.new(secret_key)
    # block cipher length must be a multiple of 8
    padding = ''
    if (len(code) % 8) <> 0:
        padding = 'X' * (8 - (len(code) % 8))
    return base64.b64encode(encryption_object.encrypt(code + padding))

wsgi/satchmo/satchmo/apps/payment/modules/sagepay/models.py
import config
PAYMENT_PROCESSOR=True

wsgi/satchmo/satchmo/apps/payment/modules/sagepay/forms.py
"""Sage Pay Form"""
from django import forms
from django.utils.translation import ugettext as _
from livesettings import config_value
from payment.forms import CreditPayShipForm, MONTHS
from payment.modules.sagepay.config import REQUIRES_ISSUE_NUMBER
import datetime
import logging

log = logging.getLogger('payment.sagepay.forms')

class SagePayShipForm(CreditPayShipForm):
    """Adds fields required by Sage Pay to the Credit form."""
    
    card_holder = forms.CharField(max_length=75, required=False)
    month_start = forms.ChoiceField(choices=[(1, '--')]+MONTHS, required=False)
    year_start = forms.ChoiceField(required=False)
    issue_num = forms.CharField(max_length=2, required=False)
    
    def __init__(self, request, paymentmodule, *args, **kwargs):
        super(SagePayShipForm, self).__init__(request, paymentmodule, *args, **kwargs)
        cf = self.fields['card_holder']
        if (not cf.initial) or cf.initial == "":
            user = request.user
            if user and user.is_authenticated() and user.contact_set.count() > 0:
                cf.initial = self.tempContact.full_name
        self.requires_issue_number = REQUIRES_ISSUE_NUMBER
        num_years = config_value('PAYMENT', 'CC_NUM_YEARS')
        year_now = datetime.date.today().year
        self.fields['year_start'].choices = [(year, year) for year in range(year_now, year_now-num_years-1, -1)]

    def save(self, request, cart, contact, payment_module, data=None):
        """Save the order and the credit card details."""
        super(SagePayShipForm, self).save(request, cart, contact, payment_module)
        if data is None:
            data = self.cleaned_data 
        log.debug("data: %s", data)                       
        card_holder=data.get('card_holder', '')
        if not card_holder:
            card_holder = contact.full_name
        self.cc.card_holder = card_holder
        month_start = data.get('month_start', None)
        year_start = data.get('year_start', None)
        if month_start:
            try:
                month_start = int(month_start)
            except ValueError:
                log.warn("Could not parse month_start int from %s on order for order: %s", month_start, self.order)
                month_start = 1
                # TODO: raise some error to be caught by processor
        else:
            month_start=None
            
        if year_start:
            try:
                year_start = int(year_start)
            except ValueError:
                log.warn("Could not parse year_start int from %s on order for order: %s", year_start, self.order)
                year_start = 1
        else:
            year_start=None
        
        issue_num = data.get('issue_num', "")
        
        self.cc.start_month=month_start
        self.cc.start_year=year_start
        self.cc.issue_num=issue_num
        self.cc.save()

    def clean_card_holder(self):
        ch = self.cleaned_data['card_holder']
        if (not ch) or ch == "":
            fn = self.tempContact.full_name
            self.cleaned_data['card_holder'] = fn
            log.debug('Setting card_holder to contact full name: %s', fn)
        else:
            log.debug('Card holder OK')

    def clean_month_start(self):
        data = self.cleaned_data
        
        self._maybe_require(data, 'month_start', _('You must provide a starting month when using this type of card.'))

        if data['month_start']:
            try:
                v = int(self.cleaned_data['month_start'])
            except ValueError:
                raise forms.ValidationError(_("This must be a number"))
            
            if not v>0 and v<13:
                raise forms.ValidationError(_("Out of range, must be 1-12"))
            
    def clean_year_start(self):
        data = self.cleaned_data
        self._maybe_require(data, 'credit_type', _('You must provide a starting year when using this type of card.'))
        
        if data['year_start']:
            try:
                v = int(self.cleaned_data['year_start'])
            except ValueError:
                raise forms.ValidationError(_("This must be a number"))

            if not v>0 and v<13:
                raise forms.ValidationError(_("Out of range, must be 1-12"))

    def clean_issue_num(self):
        data = self.cleaned_data
        self._maybe_require(data, 'issue_num', _('You must provide an issue number when using this type of card.'))

    def _maybe_require(self, data, field, message):
        if data['credit_type'] in REQUIRES_ISSUE_NUMBER and not (data[field]):
            raise forms.ValidationError(message)

wsgi/satchmo/satchmo/apps/payment/modules/sagepay/views.py
"""Sage Pay checkout custom views"""

from django import http
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext as _
from livesettings import config_get_group
from payment.views import payship, confirm
import logging
from satchmo_utils.dynamic import lookup_template

log = logging.getLogger('sagepay.views')
    
def pay_ship_info(request):
    return payship.credit_pay_ship_info(request, 
            config_get_group('PAYMENT_SAGEPAY'),
            template="shop/checkout/sagepay/pay_ship.html")
    
def confirm_info(request, template='shop/checkout/sagepay/confirm.html', extra_context={}):
    payment_module = config_get_group('PAYMENT_SAGEPAY')
    controller = confirm.ConfirmController(request, payment_module)
    controller.templates['CONFIRM'] = template
    controller.extra_context = extra_context
    controller.onForm = secure3d_form_handler
    controller.confirm()
    return controller.response
            
def confirm_secure3d(request, secure3d_template='shop/checkout/sagepay/secure3d_form.html', 
    confirm_template='shop/checkout/confirm.html', extra_context={}):
    """Handles confirming an order and processing the charges when secured by secure3d.
 
    """
    payment_module = config_get_group('PAYMENT_SAGEPAY')
    controller = confirm.ConfirmController(request, payment_module, extra_context=extra_context)
    controller.template['CONFIRM'] = confirm_template
    if not controller.sanity_check():
        return controller.response
    
    auth3d = request.session.get('3D', None)
    if not auth3d:
        controller.processorMessage = _('3D Secure transaction expired. Please try again.')

    else:
        if request.method == "POST":
            returnMD = request.POST.get('MD', None)
            if not returnMD:
                template = lookup_template(payment_module, secure3d_template)
                ctx = RequestContext(request, {'order': controller.order, 'auth': auth3d })
                return render_to_response(template, context_instance=ctx)

            elif returnMD == auth3d['MD']:
                pares = request.POST.get('PaRes', None)
                controller.processor.prepare_data(controller.order)
                controller.processor.prepare_data3d(returnMD, pares)
                if controller.process():
                    return controller.onSuccess(controller)
                else:
                    controller.processorMessage = _('3D Secure transaction was not approved by payment gateway. Please contact us.')
        else:
            template = lookup_template(payment_module, secure3d_template)
            ctx =RequestContext(request, {
                'order': controller.order, 'auth': auth3d 
                })
            return render_to_response(template, context_instance=ctx)

    return secure3d_form_handler(controller)

def secure3d_form_handler(controller):
    """At the confirmation step, sage pay may ask for a secure3d authentication.  This method
    catches that, and if so, sends to that step, otherwise the form as normal"""
    
    if controller.processorReasonCode == '3DAUTH':
        log.debug('caught secure 3D request for order #%i, putting 3D into session as %s', 
            controller.order.id, controller.processorReasonCode)
            
        redirectUrl = controller.lookup_url('satchmo_checkout-secure3d')
        controller.processor.response['TermUrl'] = redirectUrl
        controller.request.session['3D'] = controller.processorReasonCode
        return http.HttpResponseRedirect(redirectUrl)
    
    return controller.onForm(controller)

wsgi/satchmo/satchmo/apps/payment/templates/shop/checkout/sagepay/confirm.html
{% extends "shop/checkout/base_confirm.html" %}
{% load i18n %}
{% load satchmo_currency %}
{# this is the credit-card confirm template #}

{% block errorheader %}{% trans "The following error was returned while trying to process your card.  Please correct and resubmit" %}{% endblock %}

{% block navbar %}
   <li class="first"><a href="{{ shop_base }}/">{% trans "Home" %}</a></li>
   <li>{% trans "Checkout" %}</li>
{% endblock %}

{% block payment_display %}
<h4>{% trans "Payment" %}</h4>
{% if not PAYMENT_LIVE %}<b>PAYMENT TEST MODE</b><br/>{% endif %}
{% with order.credit_card.credit_type as credit_card_type %}
{% with order.credit_card.display_cc as credit_card_number %}
{% with order.balance|currency as order_total %}
{% blocktrans %}Your {{ credit_card_type }} card ending in {{ credit_card_number }} will be charged {{ order_total }}.{% endblocktrans %}
{% endwith %}
{% endwith %}
{% endwith %}
{% endblock %}

wsgi/satchmo/satchmo/apps/payment/templates/shop/checkout/sagepay/pay_ship.html
{% extends "shop/checkout/base_pay_ship.html" %}
{% load i18n satchmo_util %}
{# credit card pay_ship version - we just need to collect CC info #}

{% block extra-head %}
{{ block.super }}
{% include "shop/_jquery.html" %}
{% include "shop/_jquery_form.html" %}
{% blackbird_logging %}
<script type="text/javascript" src="{{ STATIC_URL }}js/satchmo_pay_ship.js"></script>
<script type="text/javascript"><!--
$(function() {satchmo.setup_issue_fields({{ form.requires_issue_number|as_json }})});
-->
</script>
{% endblock %}

{% block payment_table %}
    <tr><td><h4>{% trans "Payment Information" %}</h4></td></tr>
    {% if not PAYMENT_LIVE %}
    <tr><td valign="top"><b>TEST MODE</b></td><td><i>Use Visa 4111111111111111 for CC#<br/>any future date for expiration<br/>any 3 digit CCV</i></td></tr>
    {% endif %}

    <tr><td><label for="id_card_holder">{% trans "Card Holder" %}</label></td> <td>{{ form.card_holder }}</td></tr>
    {% if form.card_holder.errors %}<tr><td></td><td>*** {{ form.card_holder.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_credit_type">{% trans "Type of credit card" %}</label></td> <td>{{ form.credit_type }}</td></tr>
    {% if form.credit_type.errors %}<tr><td></td><td>*** {{ form.credit_type.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_credit_number">{% trans "Credit card number" %}</label></td><td> {{ form.credit_number }}</td></tr>
    {% if form.credit_number.errors %}<tr><td></td><td>*** {{ form.credit_number.errors|join:", " }}</td></tr>{% endif %}

    <tr class="issue"><td><label for="id_issue_num">{% trans "Issue number" %}</label></td><td> {{ form.issue_num }}</td></tr>
    {% if form.issue_num.errors %}<tr><td></td><td>*** {{ form.issue_num.errors|join:", " }}</td></tr>{% endif %}

    <tr class="issue"><td><label for="id_year_start">{% trans "Issue date" %}</label><label for="id_year_start"></label></td><td> {{ form.month_start}} {{ form.year_start }}</td></tr>
    {% if form.year_start.errors %}<tr><td></td><td>*** {{ form.year_start.errors|join:", " }}</td></tr>{% endif %}
    {% if form.month_start.errors %}<tr><td></td><td>*** {{ form.month_start.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_month_expires">{% trans "Expiration date" %}</label><label for="id_year_expires"></label></td><td> {{ form.month_expires }} {{form.year_expires}}</td></tr>
    {% if form.year_expires.errors %}<tr><td></td><td>*** {{ form.year_expires.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_ccv">{% trans "CCV" %}</label></td><td> {{ form.ccv}}</td></tr>
    {% if form.ccv.errors %}<tr><td></td><td>*** {{ form.ccv.errors|join:", " }}</td></tr>{% endif %}

{% endblock %}

wsgi/satchmo/satchmo/apps/payment/templates/shop/checkout/sagepay/secure3d_form.html
{% extends "base_satchmo.html" %}
{% load i18n %}
{% block extra-head %}
<script type="text/javascript">
$(function() {
	$('#3dform')[0].submit()
});
</script>
{% endblock %}

{% block content %}
<form id="3dform" name="3dform" action="{{ bankURL }}" method="POST">
	<input type="hidden" name="PaReq" value="{{ pareq }}" />
	<input type="hidden" name="TermUrl" value="{{ TermUrl }}" />
	<input type="hidden" name="MD" value="{{ md }}" />
	<noscript>
		<p>{% trans 'Please click the button below to authenticate your card.' %}</p>
		<input type="submit" value="{% trans 'Authenticate' %}" />
	</noscript>
</form>
{% endblock %}